"""baseline schema

Revision ID: 000_baseline_schema
Revises: 
Create Date: 2026-08-03 00:18:34.583090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '000_baseline_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dm_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dm_conversations_id'), 'dm_conversations', ['id'], unique=False)
    op.create_table('motivational_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('notification_context', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motivational_quotes_category'), 'motivational_quotes', ['category'], unique=False)
    op.create_index(op.f('ix_motivational_quotes_id'), 'motivational_quotes', ['id'], unique=False)
    op.create_index(op.f('ix_motivational_quotes_is_active'), 'motivational_quotes', ['is_active'], unique=False)
    op.create_index(op.f('ix_motivational_quotes_notification_context'), 'motivational_quotes', ['notification_context'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('diet', sa.String(length=16), nullable=False),
    sa.Column('servings', sa.Float(), nullable=False),
    sa.Column('serving_grams', sa.Float(), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fibre_g', sa.Float(), nullable=False),
    sa.Column('protein_pct_kcal', sa.Float(), nullable=False),
    sa.Column('prep_min', sa.Integer(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_category'), 'recipes', ['category'], unique=False)
    op.create_index(op.f('ix_recipes_diet'), 'recipes', ['diet'], unique=False)
    op.create_index(op.f('ix_recipes_external_id'), 'recipes', ['external_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('goals', sa.String(length=255), nullable=True),
    sa.Column('goal_tag', sa.String(length=128), nullable=True),
    sa.Column('difficulty', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('needs_password_reset', sa.Boolean(), nullable=False),
    sa.Column('subscription_status', sa.String(length=32), nullable=False),
    sa.Column('subscription_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('razorpay_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('preferred_language', sa.String(length=32), nullable=True),
    sa.Column('stack_visibility', sa.Boolean(), nullable=False),
    sa.Column('profile_photo_url', sa.String(length=512), nullable=True),
    sa.Column('pose_calibration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_razorpay_subscription_id'), 'users', ['razorpay_subscription_id'], unique=False)
    op.create_table('workout_catalog_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=255), nullable=False),
    sa.Column('body_part', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('equipment', sa.String(length=128), nullable=False),
    sa.Column('difficulty', sa.String(length=64), nullable=False),
    sa.Column('met_value', sa.Float(), nullable=True),
    sa.Column('goal_tag', sa.String(length=128), nullable=False),
    sa.Column('sets_recommended', sa.String(length=32), nullable=True),
    sa.Column('reps_recommended', sa.String(length=32), nullable=True),
    sa.Column('rest_time_sec', sa.Integer(), nullable=True),
    sa.Column('recommended_weight_kg', sa.String(length=64), nullable=True),
    sa.Column('video_url', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_catalog_v2_body_part'), 'workout_catalog_v2', ['body_part'], unique=False)
    op.create_index(op.f('ix_workout_catalog_v2_difficulty'), 'workout_catalog_v2', ['difficulty'], unique=False)
    op.create_index(op.f('ix_workout_catalog_v2_equipment'), 'workout_catalog_v2', ['equipment'], unique=False)
    op.create_index(op.f('ix_workout_catalog_v2_exercise_name'), 'workout_catalog_v2', ['exercise_name'], unique=False)
    op.create_index(op.f('ix_workout_catalog_v2_goal_tag'), 'workout_catalog_v2', ['goal_tag'], unique=False)
    op.create_index(op.f('ix_workout_catalog_v2_id'), 'workout_catalog_v2', ['id'], unique=False)
    op.create_index(op.f('ix_workout_catalog_v2_type'), 'workout_catalog_v2', ['type'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('activity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("type IN ('pr', 'streak_milestone', 'thread_joined')", name='ck_activity_events_type'),
    sa.CheckConstraint("visibility IN ('friends', 'private')", name='ck_activity_events_visibility'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_events_created_at'), 'activity_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_events_deleted_at'), 'activity_events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_activity_events_id'), 'activity_events', ['id'], unique=False)
    op.create_index(op.f('ix_activity_events_type'), 'activity_events', ['type'], unique=False)
    op.create_index(op.f('ix_activity_events_user_id'), 'activity_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_activity_events_visibility'), 'activity_events', ['visibility'], unique=False)
    op.create_table('ai_food_meal_entries',
    sa.Column('ai_meal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=32), nullable=False),
    sa.Column('food_name', sa.String(length=200), nullable=False),
    sa.Column('quantity_g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('calories', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('protein', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('carbs', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fat', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fibre', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('estimated_serving_size', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ai_meal_id')
    )
    op.create_index(op.f('ix_ai_food_meal_entries_log_date'), 'ai_food_meal_entries', ['log_date'], unique=False)
    op.create_index(op.f('ix_ai_food_meal_entries_user_id'), 'ai_food_meal_entries', ['user_id'], unique=False)
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('cost_inr', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('endpoint', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_usage_feature_created', 'ai_usage_logs', ['feature', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_created_at'), 'ai_usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_user_id'), 'ai_usage_logs', ['user_id'], unique=False)
    op.create_index('ix_ai_usage_user_created', 'ai_usage_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('winner_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed', 'cancelled')", name='ck_challenges_status'),
    sa.CheckConstraint("type IN ('streak_battle', 'workout_count')", name='ck_challenges_type'),
    sa.CheckConstraint('end_date >= start_date', name='ck_challenges_date_order'),
    sa.CheckConstraint('target > 0', name='ck_challenges_target_positive'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_creator_id'), 'challenges', ['creator_id'], unique=False)
    op.create_index(op.f('ix_challenges_end_date'), 'challenges', ['end_date'], unique=False)
    op.create_index(op.f('ix_challenges_id'), 'challenges', ['id'], unique=False)
    op.create_index(op.f('ix_challenges_start_date'), 'challenges', ['start_date'], unique=False)
    op.create_index(op.f('ix_challenges_status'), 'challenges', ['status'], unique=False)
    op.create_index(op.f('ix_challenges_type'), 'challenges', ['type'], unique=False)
    op.create_index(op.f('ix_challenges_winner_user_id'), 'challenges', ['winner_user_id'], unique=False)
    op.create_table('daily_nutrition_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('total_calories', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('total_protein_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_carbs_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_fat_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_fiber_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_water_l', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('target_calories', sa.Integer(), nullable=True),
    sa.Column('target_protein_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('target_carbs_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('target_fat_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('target_fiber_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('target_water_l', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('calories_remaining', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('is_goal_met', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id'),
    sa.UniqueConstraint('user_id', 'log_date', name='unique_user_date')
    )
    op.create_index(op.f('ix_daily_nutrition_logs_user_id'), 'daily_nutrition_logs', ['user_id'], unique=False)
    op.create_table('friend_request_daily_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'request_date', name='uq_friend_request_daily_counts_user_date')
    )
    op.create_index(op.f('ix_friend_request_daily_counts_id'), 'friend_request_daily_counts', ['id'], unique=False)
    op.create_index(op.f('ix_friend_request_daily_counts_request_date'), 'friend_request_daily_counts', ['request_date'], unique=False)
    op.create_index(op.f('ix_friend_request_daily_counts_user_id'), 'friend_request_daily_counts', ['user_id'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'blocked')", name='ck_friendships_status'),
    sa.CheckConstraint('user_id <> friend_id', name='ck_friendships_not_self'),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friendships_friend_id'), 'friendships', ['friend_id'], unique=False)
    op.create_index(op.f('ix_friendships_id'), 'friendships', ['id'], unique=False)
    op.create_index(op.f('ix_friendships_status'), 'friendships', ['status'], unique=False)
    op.create_index(op.f('ix_friendships_user_id'), 'friendships', ['user_id'], unique=False)
    op.create_table('global_exercises',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('body_part', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('equipment', sa.Text(), nullable=False),
    sa.Column('muscles_primary', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('muscles_secondary', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('met_value', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Text(), nullable=True),
    sa.Column('is_compound', sa.Boolean(), nullable=True),
    sa.Column('catalog_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['workout_catalog_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_exercises_catalog_id'), 'global_exercises', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_global_exercises_id'), 'global_exercises', ['id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Integer(), nullable=True),
    sa.Column('carbs', sa.Integer(), nullable=True),
    sa.Column('fat', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_id'), 'meals', ['id'], unique=False)
    op.create_table('monthly_meal_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('budget_level', sa.String(length=32), nullable=False),
    sa.Column('regional_food_styles_json', sa.Text(), nullable=True),
    sa.Column('diet_type', sa.String(length=32), nullable=True),
    sa.Column('onboarding_snapshot_json', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('target_kcal', sa.Integer(), nullable=True),
    sa.Column('target_protein_g', sa.Integer(), nullable=True),
    sa.Column('target_carbs_g', sa.Integer(), nullable=True),
    sa.Column('target_fat_g', sa.Integer(), nullable=True),
    sa.Column('target_fiber_g', sa.Integer(), nullable=True),
    sa.Column('week_start_day', sa.Integer(), nullable=True),
    sa.Column('week_end_day', sa.Integer(), nullable=True),
    sa.Column('generation_mode', sa.String(length=32), nullable=False),
    sa.Column('day_regens_used', sa.Integer(), nullable=False),
    sa.Column('day_regens_limit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month', 'year', 'week_start_day', name='uq_meal_plan_user_month_week')
    )
    op.create_index(op.f('ix_monthly_meal_plans_user_id'), 'monthly_meal_plans', ['user_id'], unique=False)
    op.create_table('monthly_workout_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('focus_muscle', sa.String(length=64), nullable=True),
    sa.Column('focus_muscles_json', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('onboarding_snapshot_json', sa.Text(), nullable=True),
    sa.Column('day_regens_used', sa.Integer(), nullable=False),
    sa.Column('day_regens_limit', sa.Integer(), nullable=False),
    sa.Column('month_plan_regens_used', sa.Integer(), nullable=False),
    sa.Column('month_plan_regens_limit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month', 'year', name='uq_workout_plan_user_month')
    )
    op.create_index(op.f('ix_monthly_workout_plans_user_id'), 'monthly_workout_plans', ['user_id'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('event_key', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expo_ticket_id', sa.String(length=160), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_log_category'), 'notification_log', ['category'], unique=False)
    op.create_index(op.f('ix_notification_log_created_at'), 'notification_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_log_event_key'), 'notification_log', ['event_key'], unique=False)
    op.create_index(op.f('ix_notification_log_id'), 'notification_log', ['id'], unique=False)
    op.create_index(op.f('ix_notification_log_sent_at'), 'notification_log', ['sent_at'], unique=False)
    op.create_index(op.f('ix_notification_log_status'), 'notification_log', ['status'], unique=False)
    op.create_index(op.f('ix_notification_log_user_id'), 'notification_log', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferences_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('push_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expo_push_token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'expo_push_token', name='uq_push_token_user_token')
    )
    op.create_index(op.f('ix_push_tokens_expo_push_token'), 'push_tokens', ['expo_push_token'], unique=False)
    op.create_index(op.f('ix_push_tokens_id'), 'push_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_push_tokens_is_active'), 'push_tokens', ['is_active'], unique=False)
    op.create_index(op.f('ix_push_tokens_user_id'), 'push_tokens', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('billing_cycle', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('price_inr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('razorpay_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=128), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=128), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('swap_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('swap_type', sa.String(length=16), nullable=False),
    sa.Column('swap_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swap_usage_logs_user_id'), 'swap_usage_logs', ['user_id'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('gym_name', sa.String(length=255), nullable=False),
    sa.Column('gym_place_id', sa.String(length=255), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('referral_code', sa.String(length=80), nullable=True),
    sa.Column('referral_description', sa.Text(), nullable=True),
    sa.Column('referral_discount_text', sa.String(length=160), nullable=True),
    sa.Column('referral_viewed_count', sa.Integer(), nullable=False),
    sa.Column('referral_copied_count', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed', 'cancelled')", name='ck_threads_status'),
    sa.CheckConstraint("visibility IN ('public', 'private')", name='ck_threads_visibility'),
    sa.CheckConstraint('max_members > 0', name='ck_threads_max_members_positive'),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_expires_at'), 'threads', ['expires_at'], unique=False)
    op.create_index(op.f('ix_threads_gym_place_id'), 'threads', ['gym_place_id'], unique=False)
    op.create_index(op.f('ix_threads_host_user_id'), 'threads', ['host_user_id'], unique=False)
    op.create_index(op.f('ix_threads_id'), 'threads', ['id'], unique=False)
    op.create_index(op.f('ix_threads_scheduled_time'), 'threads', ['scheduled_time'], unique=False)
    op.create_index(op.f('ix_threads_status'), 'threads', ['status'], unique=False)
    op.create_index(op.f('ix_threads_visibility'), 'threads', ['visibility'], unique=False)
    op.create_table('user_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_date', name='uq_user_activity_per_day')
    )
    op.create_index(op.f('ix_user_activity_logs_user_id'), 'user_activity_logs', ['user_id'], unique=False)
    op.create_table('user_meal_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(length=32), nullable=False),
    sa.Column('slot_order', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('swap_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'plan_date', 'slot', 'slot_order', name='uq_user_meal_plan_user_date_slot_order')
    )
    op.create_index(op.f('ix_user_meal_plan_recipe_id'), 'user_meal_plan', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_user_meal_plan_user_id'), 'user_meal_plan', ['user_id'], unique=False)
    op.create_table('user_onboarding',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('onboarding_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('targets_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reported_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('context', sa.String(length=16), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("context IN ('profile', 'message', 'thread')", name='ck_user_reports_context'),
    sa.CheckConstraint("reason IN ('harassment', 'spam', 'inappropriate_content', 'fake_profile', 'other')", name='ck_user_reports_reason'),
    sa.CheckConstraint("status IN ('open', 'reviewed', 'actioned')", name='ck_user_reports_status'),
    sa.CheckConstraint('reporter_id <> reported_user_id', name='ck_user_reports_not_self'),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_reports_context'), 'user_reports', ['context'], unique=False)
    op.create_index(op.f('ix_user_reports_created_at'), 'user_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_reports_id'), 'user_reports', ['id'], unique=False)
    op.create_index(op.f('ix_user_reports_reason'), 'user_reports', ['reason'], unique=False)
    op.create_index(op.f('ix_user_reports_reference_id'), 'user_reports', ['reference_id'], unique=False)
    op.create_index(op.f('ix_user_reports_reported_user_id'), 'user_reports', ['reported_user_id'], unique=False)
    op.create_index(op.f('ix_user_reports_reporter_id'), 'user_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_user_reports_status'), 'user_reports', ['status'], unique=False)
    op.create_table('user_supplement_stack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity_note', sa.String(length=255), nullable=True),
    sa.Column('timing_type', sa.String(length=32), nullable=False),
    sa.Column('timing_value', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("category IN ('protein', 'creatine', 'preworkout', 'bcaa', 'multivitamin', 'other')", name='ck_user_supplement_stack_category'),
    sa.CheckConstraint("timing_type IN ('time_of_day', 'relative_to_workout', 'custom_text')", name='ck_user_supplement_stack_timing_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_supplement_stack_category'), 'user_supplement_stack', ['category'], unique=False)
    op.create_index(op.f('ix_user_supplement_stack_id'), 'user_supplement_stack', ['id'], unique=False)
    op.create_index(op.f('ix_user_supplement_stack_sort_order'), 'user_supplement_stack', ['sort_order'], unique=False)
    op.create_index(op.f('ix_user_supplement_stack_user_id'), 'user_supplement_stack', ['user_id'], unique=False)
    op.create_table('water_intake_log',
    sa.Column('water_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('total_water_l', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('target_water_l', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('is_target_met', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('water_id'),
    sa.UniqueConstraint('user_id', 'log_date', name='unique_user_water_date')
    )
    op.create_index(op.f('ix_water_intake_log_user_id'), 'water_intake_log', ['user_id'], unique=False)
    op.create_table('weight_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('weight_lb', sa.Float(), nullable=True),
    sa.Column('unit_system', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('log_date', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_weight_log_user_date')
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_day_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('server_kcal_total', sa.Float(), nullable=False),
    sa.Column('streak_incremented', sa.Boolean(), nullable=False),
    sa.Column('ai_tracking', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_session_id'), 'workout_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_table('challenge_participants',
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target_reached_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('invited', 'joined', 'declined', 'left')", name='ck_challenge_participants_status'),
    sa.CheckConstraint('progress >= 0', name='ck_challenge_participants_progress_nonnegative'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('challenge_id', 'user_id')
    )
    op.create_index(op.f('ix_challenge_participants_status'), 'challenge_participants', ['status'], unique=False)
    op.create_index(op.f('ix_challenge_participants_target_reached_at'), 'challenge_participants', ['target_reached_at'], unique=False)
    op.create_table('daily_meal_plan_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('is_cheat_day', sa.Boolean(), nullable=True),
    sa.Column('total_calories', sa.Integer(), nullable=False),
    sa.Column('total_protein_g', sa.Integer(), nullable=False),
    sa.Column('total_carbs_g', sa.Integer(), nullable=False),
    sa.Column('total_fat_g', sa.Integer(), nullable=False),
    sa.Column('total_fiber_g', sa.Integer(), nullable=False),
    sa.Column('meals_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['monthly_meal_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'day', name='uq_meal_plan_day')
    )
    op.create_index(op.f('ix_daily_meal_plan_entries_plan_id'), 'daily_meal_plan_entries', ['plan_id'], unique=False)
    op.create_table('daily_workout_plan_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('is_rest_day', sa.Boolean(), nullable=True),
    sa.Column('split_name', sa.String(length=120), nullable=False),
    sa.Column('focus_muscles_json', sa.Text(), nullable=False),
    sa.Column('exercises_json', sa.Text(), nullable=False),
    sa.Column('estimated_duration_min', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['monthly_workout_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'day', name='uq_workout_plan_day')
    )
    op.create_index(op.f('ix_daily_workout_plan_entries_plan_id'), 'daily_workout_plan_entries', ['plan_id'], unique=False)
    op.create_table('feed_reactions',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("type IN ('flame', 'clap')", name='ck_feed_reactions_type'),
    sa.ForeignKeyConstraint(['event_id'], ['activity_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'user_id', 'type')
    )
    op.create_table('global_exercise_labels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.BigInteger(), nullable=False),
    sa.Column('language_tag', sa.String(length=32), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['global_exercises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'language_tag', name='uq_global_exercise_label_language')
    )
    op.create_index(op.f('ix_global_exercise_labels_exercise_id'), 'global_exercise_labels', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_global_exercise_labels_language_tag'), 'global_exercise_labels', ['language_tag'], unique=False)
    op.create_table('meal_entries',
    sa.Column('meal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('food_id', sa.BigInteger(), nullable=True),
    sa.Column('food_name', sa.String(length=200), nullable=False),
    sa.Column('quantity_g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('calories_per_100g', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('protein_per_100g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('carbs_per_100g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fat_per_100g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fiber_per_100g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_calories', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('total_protein_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_carbs_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_fat_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_fiber_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['daily_nutrition_logs.log_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meal_id')
    )
    op.create_index(op.f('ix_meal_entries_food_id'), 'meal_entries', ['food_id'], unique=False)
    op.create_index(op.f('ix_meal_entries_log_id'), 'meal_entries', ['log_id'], unique=False)
    op.create_index(op.f('ix_meal_entries_user_id'), 'meal_entries', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('dm_conversation_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('reply_to_message_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("type IN ('text', 'location', 'referral', 'workout_share', 'stack_share', 'system')", name='ck_messages_type'),
    sa.CheckConstraint('(thread_id IS NOT NULL) <> (dm_conversation_id IS NOT NULL)', name='ck_messages_one_conversation'),
    sa.ForeignKeyConstraint(['dm_conversation_id'], ['dm_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_deleted_at'), 'messages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_messages_dm_conversation_id'), 'messages', ['dm_conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_reply_to_message_id'), 'messages', ['reply_to_message_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_messages_type'), 'messages', ['type'], unique=False)
    op.create_table('thread_join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('requester_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'approved', 'declined')", name='ck_thread_join_requests_status'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'requester_user_id', name='uq_thread_join_requests_thread_requester')
    )
    op.create_index(op.f('ix_thread_join_requests_created_at'), 'thread_join_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_thread_join_requests_id'), 'thread_join_requests', ['id'], unique=False)
    op.create_index(op.f('ix_thread_join_requests_requester_user_id'), 'thread_join_requests', ['requester_user_id'], unique=False)
    op.create_index(op.f('ix_thread_join_requests_status'), 'thread_join_requests', ['status'], unique=False)
    op.create_index(op.f('ix_thread_join_requests_thread_id'), 'thread_join_requests', ['thread_id'], unique=False)
    op.create_table('thread_mutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('muted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'user_id', name='uq_thread_mutes_thread_user')
    )
    op.create_index(op.f('ix_thread_mutes_id'), 'thread_mutes', ['id'], unique=False)
    op.create_index(op.f('ix_thread_mutes_thread_id'), 'thread_mutes', ['thread_id'], unique=False)
    op.create_index(op.f('ix_thread_mutes_user_id'), 'thread_mutes', ['user_id'], unique=False)
    op.create_table('workout_session_set_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_pk', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=255), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('server_kcal', sa.Float(), nullable=False),
    sa.Column('tracking_method', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['session_pk'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_session_set_logs_session_pk'), 'workout_session_set_logs', ['session_pk'], unique=False)
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('exercise_name', sa.String(length=120), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['global_exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_exercise_id'), 'workouts', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workouts_id'), 'workouts', ['id'], unique=False)
    op.create_table('dm_conversation_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dm_conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('muted_at', sa.DateTime(), nullable=True),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dm_conversation_id'], ['dm_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dm_conversation_id', 'user_id', name='uq_dm_conversation_members_conversation_user')
    )
    op.create_index(op.f('ix_dm_conversation_members_dm_conversation_id'), 'dm_conversation_members', ['dm_conversation_id'], unique=False)
    op.create_index(op.f('ix_dm_conversation_members_id'), 'dm_conversation_members', ['id'], unique=False)
    op.create_index(op.f('ix_dm_conversation_members_user_id'), 'dm_conversation_members', ['user_id'], unique=False)
    op.create_table('strength_lifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.BigInteger(), nullable=True),
    sa.Column('exercise_name', sa.String(length=120), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['global_exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strength_lifts_date'), 'strength_lifts', ['date'], unique=False)
    op.create_index(op.f('ix_strength_lifts_exercise_id'), 'strength_lifts', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_strength_lifts_exercise_name'), 'strength_lifts', ['exercise_name'], unique=False)
    op.create_index(op.f('ix_strength_lifts_id'), 'strength_lifts', ['id'], unique=False)
    op.create_index(op.f('ix_strength_lifts_user_id'), 'strength_lifts', ['user_id'], unique=False)
    op.create_index(op.f('ix_strength_lifts_workout_id'), 'strength_lifts', ['workout_id'], unique=False)
    op.create_table('thread_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("role IN ('host', 'member')", name='ck_thread_members_role'),
    sa.CheckConstraint("status IN ('invited', 'joined', 'declined')", name='ck_thread_members_status'),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'user_id', name='uq_thread_members_thread_user')
    )
    op.create_index(op.f('ix_thread_members_id'), 'thread_members', ['id'], unique=False)
    op.create_index(op.f('ix_thread_members_joined_at'), 'thread_members', ['joined_at'], unique=False)
    op.create_index(op.f('ix_thread_members_role'), 'thread_members', ['role'], unique=False)
    op.create_index(op.f('ix_thread_members_status'), 'thread_members', ['status'], unique=False)
    op.create_index(op.f('ix_thread_members_thread_id'), 'thread_members', ['thread_id'], unique=False)
    op.create_index(op.f('ix_thread_members_user_id'), 'thread_members', ['user_id'], unique=False)

    # Food catalog tables are managed outside Base.metadata (see food_catalog_service).
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))
    op.execute(
        sa.text(
            """
            CREATE TABLE food_categories (
                category_id BIGSERIAL PRIMARY KEY,
                category_name VARCHAR(80) NOT NULL UNIQUE
            )
            """
        )
    )
    op.execute(
        sa.text(
            """
            CREATE TABLE food_items (
                food_id BIGSERIAL PRIMARY KEY,
                source_food_id BIGINT NULL,
                food_name VARCHAR(200) NOT NULL,
                category_id BIGINT NOT NULL REFERENCES food_categories(category_id),
                calories_per_100g NUMERIC(9,2) NOT NULL,
                protein_g NUMERIC(9,2) NOT NULL DEFAULT 0,
                carbs_g NUMERIC(9,2) NOT NULL DEFAULT 0,
                fat_g NUMERIC(9,2) NOT NULL DEFAULT 0,
                fiber_g NUMERIC(9,2) NOT NULL DEFAULT 0,
                sugar_g NUMERIC(9,2) NOT NULL DEFAULT 0,
                sodium_mg NUMERIC(10,2) NOT NULL DEFAULT 0,
                saturated_fat_g NUMERIC(9,2) NOT NULL DEFAULT 0,
                cholesterol_mg NUMERIC(10,2) NOT NULL DEFAULT 0,
                potassium_mg NUMERIC(10,2) NOT NULL DEFAULT 0,
                calcium_mg NUMERIC(10,2) NOT NULL DEFAULT 0,
                iron_mg NUMERIC(9,2) NOT NULL DEFAULT 0,
                vitamin_c_mg NUMERIC(9,2) NOT NULL DEFAULT 0,
                glycemic_index INT NULL,
                serving_size_g NUMERIC(9,2) NOT NULL DEFAULT 100,
                unit_label VARCHAR(64) NULL,
                unit_grams NUMERIC(9,2) NULL,
                kcal_per_unit NUMERIC(9,2) NULL,
                protein_per_unit NUMERIC(9,2) NULL,
                carbs_per_unit NUMERIC(9,2) NULL,
                fat_per_unit NUMERIC(9,2) NULL,
                is_supplement BOOLEAN NOT NULL DEFAULT FALSE,
                is_composite BOOLEAN NOT NULL DEFAULT FALSE,
                region VARCHAR(32) NULL,
                is_vegetarian BOOLEAN NOT NULL DEFAULT TRUE,
                is_vegan BOOLEAN NOT NULL DEFAULT FALSE,
                is_gluten_free BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
    )
    op.execute(sa.text("CREATE INDEX idx_food_items_food_name ON food_items(food_name)"))
    op.execute(sa.text("CREATE INDEX idx_food_items_food_name_lower ON food_items((LOWER(food_name)))"))
    op.execute(sa.text("CREATE INDEX idx_food_items_category_id ON food_items(category_id)"))
    op.execute(sa.text("CREATE INDEX idx_food_items_food_name_trgm ON food_items USING gin (food_name gin_trgm_ops)"))
    op.execute(
        sa.text(
            """
            CREATE TABLE food_item_labels (
                id BIGSERIAL PRIMARY KEY,
                food_id BIGINT NOT NULL REFERENCES food_items(food_id) ON DELETE CASCADE,
                language_tag VARCHAR(32) NOT NULL,
                label TEXT NOT NULL,
                aliases TEXT[] NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT uq_food_item_label_language UNIQUE (food_id, language_tag)
            )
            """
        )
    )
    op.execute(sa.text("CREATE INDEX ix_food_item_labels_food_id ON food_item_labels(food_id)"))
    op.execute(sa.text("CREATE INDEX ix_food_item_labels_language_tag ON food_item_labels(language_tag)"))
    op.execute(sa.text("CREATE INDEX ix_food_item_labels_label_lower ON food_item_labels((LOWER(label)))"))
    op.execute(
        sa.text(
            """
            CREATE TABLE food_category_labels (
                id BIGSERIAL PRIMARY KEY,
                category_id BIGINT NOT NULL REFERENCES food_categories(category_id) ON DELETE CASCADE,
                language_tag VARCHAR(32) NOT NULL,
                label TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT uq_food_category_label_language UNIQUE (category_id, language_tag)
            )
            """
        )
    )
    op.execute(sa.text("CREATE INDEX ix_food_category_labels_category_id ON food_category_labels(category_id)"))
    op.execute(sa.text("CREATE INDEX ix_food_category_labels_language_tag ON food_category_labels(language_tag)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DROP TABLE IF EXISTS food_category_labels CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS food_item_labels CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS food_items CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS food_categories CASCADE"))
    op.drop_index(op.f('ix_thread_members_user_id'), table_name='thread_members')
    op.drop_index(op.f('ix_thread_members_thread_id'), table_name='thread_members')
    op.drop_index(op.f('ix_thread_members_status'), table_name='thread_members')
    op.drop_index(op.f('ix_thread_members_role'), table_name='thread_members')
    op.drop_index(op.f('ix_thread_members_joined_at'), table_name='thread_members')
    op.drop_index(op.f('ix_thread_members_id'), table_name='thread_members')
    op.drop_table('thread_members')
    op.drop_index(op.f('ix_strength_lifts_workout_id'), table_name='strength_lifts')
    op.drop_index(op.f('ix_strength_lifts_user_id'), table_name='strength_lifts')
    op.drop_index(op.f('ix_strength_lifts_id'), table_name='strength_lifts')
    op.drop_index(op.f('ix_strength_lifts_exercise_name'), table_name='strength_lifts')
    op.drop_index(op.f('ix_strength_lifts_exercise_id'), table_name='strength_lifts')
    op.drop_index(op.f('ix_strength_lifts_date'), table_name='strength_lifts')
    op.drop_table('strength_lifts')
    op.drop_index(op.f('ix_dm_conversation_members_user_id'), table_name='dm_conversation_members')
    op.drop_index(op.f('ix_dm_conversation_members_id'), table_name='dm_conversation_members')
    op.drop_index(op.f('ix_dm_conversation_members_dm_conversation_id'), table_name='dm_conversation_members')
    op.drop_table('dm_conversation_members')
    op.drop_index(op.f('ix_workouts_id'), table_name='workouts')
    op.drop_index(op.f('ix_workouts_exercise_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_workout_session_set_logs_session_pk'), table_name='workout_session_set_logs')
    op.drop_table('workout_session_set_logs')
    op.drop_index(op.f('ix_thread_mutes_user_id'), table_name='thread_mutes')
    op.drop_index(op.f('ix_thread_mutes_thread_id'), table_name='thread_mutes')
    op.drop_index(op.f('ix_thread_mutes_id'), table_name='thread_mutes')
    op.drop_table('thread_mutes')
    op.drop_index(op.f('ix_thread_join_requests_thread_id'), table_name='thread_join_requests')
    op.drop_index(op.f('ix_thread_join_requests_status'), table_name='thread_join_requests')
    op.drop_index(op.f('ix_thread_join_requests_requester_user_id'), table_name='thread_join_requests')
    op.drop_index(op.f('ix_thread_join_requests_id'), table_name='thread_join_requests')
    op.drop_index(op.f('ix_thread_join_requests_created_at'), table_name='thread_join_requests')
    op.drop_table('thread_join_requests')
    op.drop_index(op.f('ix_messages_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_reply_to_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_dm_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_deleted_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_meal_entries_user_id'), table_name='meal_entries')
    op.drop_index(op.f('ix_meal_entries_log_id'), table_name='meal_entries')
    op.drop_index(op.f('ix_meal_entries_food_id'), table_name='meal_entries')
    op.drop_table('meal_entries')
    op.drop_index(op.f('ix_global_exercise_labels_language_tag'), table_name='global_exercise_labels')
    op.drop_index(op.f('ix_global_exercise_labels_exercise_id'), table_name='global_exercise_labels')
    op.drop_table('global_exercise_labels')
    op.drop_table('feed_reactions')
    op.drop_index(op.f('ix_daily_workout_plan_entries_plan_id'), table_name='daily_workout_plan_entries')
    op.drop_table('daily_workout_plan_entries')
    op.drop_index(op.f('ix_daily_meal_plan_entries_plan_id'), table_name='daily_meal_plan_entries')
    op.drop_table('daily_meal_plan_entries')
    op.drop_index(op.f('ix_challenge_participants_target_reached_at'), table_name='challenge_participants')
    op.drop_index(op.f('ix_challenge_participants_status'), table_name='challenge_participants')
    op.drop_table('challenge_participants')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_session_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_table('weight_logs')
    op.drop_index(op.f('ix_water_intake_log_user_id'), table_name='water_intake_log')
    op.drop_table('water_intake_log')
    op.drop_index(op.f('ix_user_supplement_stack_user_id'), table_name='user_supplement_stack')
    op.drop_index(op.f('ix_user_supplement_stack_sort_order'), table_name='user_supplement_stack')
    op.drop_index(op.f('ix_user_supplement_stack_id'), table_name='user_supplement_stack')
    op.drop_index(op.f('ix_user_supplement_stack_category'), table_name='user_supplement_stack')
    op.drop_table('user_supplement_stack')
    op.drop_index(op.f('ix_user_reports_status'), table_name='user_reports')
    op.drop_index(op.f('ix_user_reports_reporter_id'), table_name='user_reports')
    op.drop_index(op.f('ix_user_reports_reported_user_id'), table_name='user_reports')
    op.drop_index(op.f('ix_user_reports_reference_id'), table_name='user_reports')
    op.drop_index(op.f('ix_user_reports_reason'), table_name='user_reports')
    op.drop_index(op.f('ix_user_reports_id'), table_name='user_reports')
    op.drop_index(op.f('ix_user_reports_created_at'), table_name='user_reports')
    op.drop_index(op.f('ix_user_reports_context'), table_name='user_reports')
    op.drop_table('user_reports')
    op.drop_table('user_onboarding')
    op.drop_index(op.f('ix_user_meal_plan_user_id'), table_name='user_meal_plan')
    op.drop_index(op.f('ix_user_meal_plan_recipe_id'), table_name='user_meal_plan')
    op.drop_table('user_meal_plan')
    op.drop_index(op.f('ix_user_activity_logs_user_id'), table_name='user_activity_logs')
    op.drop_table('user_activity_logs')
    op.drop_index(op.f('ix_threads_visibility'), table_name='threads')
    op.drop_index(op.f('ix_threads_status'), table_name='threads')
    op.drop_index(op.f('ix_threads_scheduled_time'), table_name='threads')
    op.drop_index(op.f('ix_threads_id'), table_name='threads')
    op.drop_index(op.f('ix_threads_host_user_id'), table_name='threads')
    op.drop_index(op.f('ix_threads_gym_place_id'), table_name='threads')
    op.drop_index(op.f('ix_threads_expires_at'), table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_swap_usage_logs_user_id'), table_name='swap_usage_logs')
    op.drop_table('swap_usage_logs')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_push_tokens_user_id'), table_name='push_tokens')
    op.drop_index(op.f('ix_push_tokens_is_active'), table_name='push_tokens')
    op.drop_index(op.f('ix_push_tokens_id'), table_name='push_tokens')
    op.drop_index(op.f('ix_push_tokens_expo_push_token'), table_name='push_tokens')
    op.drop_table('push_tokens')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_notification_log_user_id'), table_name='notification_log')
    op.drop_index(op.f('ix_notification_log_status'), table_name='notification_log')
    op.drop_index(op.f('ix_notification_log_sent_at'), table_name='notification_log')
    op.drop_index(op.f('ix_notification_log_id'), table_name='notification_log')
    op.drop_index(op.f('ix_notification_log_event_key'), table_name='notification_log')
    op.drop_index(op.f('ix_notification_log_created_at'), table_name='notification_log')
    op.drop_index(op.f('ix_notification_log_category'), table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_monthly_workout_plans_user_id'), table_name='monthly_workout_plans')
    op.drop_table('monthly_workout_plans')
    op.drop_index(op.f('ix_monthly_meal_plans_user_id'), table_name='monthly_meal_plans')
    op.drop_table('monthly_meal_plans')
    op.drop_index(op.f('ix_meals_id'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_global_exercises_id'), table_name='global_exercises')
    op.drop_index(op.f('ix_global_exercises_catalog_id'), table_name='global_exercises')
    op.drop_table('global_exercises')
    op.drop_index(op.f('ix_friendships_user_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_status'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_friend_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_friend_request_daily_counts_user_id'), table_name='friend_request_daily_counts')
    op.drop_index(op.f('ix_friend_request_daily_counts_request_date'), table_name='friend_request_daily_counts')
    op.drop_index(op.f('ix_friend_request_daily_counts_id'), table_name='friend_request_daily_counts')
    op.drop_table('friend_request_daily_counts')
    op.drop_index(op.f('ix_daily_nutrition_logs_user_id'), table_name='daily_nutrition_logs')
    op.drop_table('daily_nutrition_logs')
    op.drop_index(op.f('ix_challenges_winner_user_id'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_type'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_status'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_start_date'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_id'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_end_date'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_creator_id'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index('ix_ai_usage_user_created', table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_user_id'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_created_at'), table_name='ai_usage_logs')
    op.drop_index('ix_ai_usage_feature_created', table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    op.drop_index(op.f('ix_ai_food_meal_entries_user_id'), table_name='ai_food_meal_entries')
    op.drop_index(op.f('ix_ai_food_meal_entries_log_date'), table_name='ai_food_meal_entries')
    op.drop_table('ai_food_meal_entries')
    op.drop_index(op.f('ix_activity_events_visibility'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_user_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_type'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_deleted_at'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_created_at'), table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_workout_catalog_v2_type'), table_name='workout_catalog_v2')
    op.drop_index(op.f('ix_workout_catalog_v2_id'), table_name='workout_catalog_v2')
    op.drop_index(op.f('ix_workout_catalog_v2_goal_tag'), table_name='workout_catalog_v2')
    op.drop_index(op.f('ix_workout_catalog_v2_exercise_name'), table_name='workout_catalog_v2')
    op.drop_index(op.f('ix_workout_catalog_v2_equipment'), table_name='workout_catalog_v2')
    op.drop_index(op.f('ix_workout_catalog_v2_difficulty'), table_name='workout_catalog_v2')
    op.drop_index(op.f('ix_workout_catalog_v2_body_part'), table_name='workout_catalog_v2')
    op.drop_table('workout_catalog_v2')
    op.drop_index(op.f('ix_users_razorpay_subscription_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_recipes_external_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_diet'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_category'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_motivational_quotes_notification_context'), table_name='motivational_quotes')
    op.drop_index(op.f('ix_motivational_quotes_is_active'), table_name='motivational_quotes')
    op.drop_index(op.f('ix_motivational_quotes_id'), table_name='motivational_quotes')
    op.drop_index(op.f('ix_motivational_quotes_category'), table_name='motivational_quotes')
    op.drop_table('motivational_quotes')
    op.drop_index(op.f('ix_dm_conversations_id'), table_name='dm_conversations')
    op.drop_table('dm_conversations')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
